import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useNavigation } from '../lib/NavContext'
import FetchFromCms from '../lib/FetchFromCms'
import PopulateNavMenu from '../lib/PopulateNavMenu'

export default function Home({categoryData}) {
  PopulateNavMenu(categoryData)
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex max-w-20' >
        asd
      </div>
    </div>
  )
}

export async function getStaticProps() {
  
  const categoryData = await FetchFromCms({
    url: "categories",
    params: {
      "fields[0]": "category_name", 
      "fields[1]": "category_slug",
      "populate[pages][fields][0]": "title",
      "populate[pages][fields][1]": "slug"
    }
  })
  return { props: { categoryData } }
  
}