import Head from 'next/head'
import Image from 'next/image'
import FetchFromCms from '../lib/FetchFromCms'
import PopulateNavMenu from '../lib/PopulateNavMenu'
import { useRouter } from 'next/router'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Link from 'next/link'


export default function Home({categoryData}) {
  PopulateNavMenu(categoryData)
  
  const router = useRouter()
  const { t } = useTranslation('common')

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex max-w-20' >
        asd
      </div>

      <div style={{margin: '20px'}}>
          <div>{t('current_locale')}: {t(router.locale)}</div>
          <div>
            <Link
              href='/'
              locale={router.locale === 'en' ? 'tr' : 'en'}>
              <button>
                {t('change_locale')}
              </button>
            </Link>
          </div>
        </div>
        
    </div>
  )
}

export async function getStaticProps({ locale }) {
  
  const categoryData = await FetchFromCms({
    url: "categories",
    params: {
      // "locale" : {(locale === "tr" ? "tr-TR" : "en")},
      "fields[0]": "category_name", 
      "fields[1]": "category_slug",
      "populate[pages][fields][0]": "title",
      "populate[pages][fields][1]": "slug"
    }
  })

  const translations = await serverSideTranslations(locale, ['common'])

  return { props: { categoryData, translations } }
}